name: PR Agent Workflow

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  pr_agent_job:
    if: github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent on pull request events
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pr-agent config
        run: |
          mkdir -p .github
          cat <<EOF > .github/pr-agent-config.yaml
          pr_reviewer:
            enabled: true
            model: gpt-4

          pr_description:
            enabled: true
          EOF

      - name: Run PR Agent
        uses: Codium-ai/pr-agent@main
        with:
          github_token: ${{ secrets.GH_SECRET_TOKEN }}
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_SECRET_TOKEN }}
